name: Reusable Node.js Tests

on:
  workflow_call:
    inputs:
      os-version:
        description: 'OS version to use (e.g., ubuntu-latest)'
        required: false
        type: string
        default: '["ubuntu-latest","macos-latest","windows-latest"]'
      node-version:
        description: 'Node.js version to use (e.g., 18.x)'
        required: true
        type: string

jobs:
  test:
    name: Test on ${{ matrix.os-version }} with Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix:
        os-version: ${{ fromJSON(inputs.os-version) }}
        node-version: ${{ fromJSON(inputs.node-version) }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test
